### ISSUE TITLE
Blizzard Support

### ISSUE THREAD

**Issue by kramrm** [DestinyItemManager/destinyitemmanager.com#4]
I think it's cool you still support Blizzard accounts.  What about Steam/Stadia?

![image](https://user-images.githubusercontent.com/48371021/87212431-387fa980-c2d3-11ea-8646-bf063e291f06.png)

**Comment by delphiactual** [comment]
In the middle of a redesign

https://github.com/DestinyItemManager/destinyitemmanager.com/tree/redesign2020
